name: autopill
description: "Ứng dụng nhắc uống thuốc thông minh - AutoPill"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2  # Dùng để lưu trạng thái đã đăng nhập
  provider: ^6.1.1            # Chỉ giữ lại 1 dòng provider ở đây

  # UI & Styling
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  percent_indicator: ^4.2.3
  fl_chart: ^0.66.0

  # State Management & Di
  get_it: ^7.6.4

  # Local Storage & Core
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1

  # Features
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

# MỤC NÀY PHẢI NẰM NGOÀI CÙNG, KHÔNG THỤT LỀ VÀO TRONG MỤC FLUTTER
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"